// 申购原因选项
export const ORDER_REASON_OPTIONS = [
  { label: '没有', value: 'not_stocked' },
  { label: '公用常用', value: 'common_public' },
  { label: '库存用完', value: 'running_out' },
  { label: '没找到', value: 'not_found' },
  { label: '不够用', value: 'not_enough' },
  { label: '追加订购', value: 'reorder' },
  { label: '大量使用', value: 'high_usage' },
  { label: '变质', value: 'degraded' },
  { label: '其他', value: 'others' },
]

export const REAGENT_CATEGORY_OPTIONS = [
  { label: '胺', value: '胺' },
  { label: '酰胺', value: '酰胺' },
  { label: '酰卤', value: '酰卤' },
  { label: '碱', value: '碱' },
  { label: '腈', value: '腈' },
  { label: '酐', value: '酐' },
  { label: '酸', value: '酸' },
  { label: '醇', value: '醇' },
  { label: '氮官能团', value: '氮官能团' },
  { label: '氮杂环卡宾', value: '氮杂环卡宾' },
  { label: '过渡金属', value: '过渡金属' },
  { label: '杂环', value: '杂环' },
  { label: '还原剂', value: '还原剂' },
  { label: '金属相关', value: '金属相关' },
  { label: '聚合物', value: '聚合物' },
  { label: '硫', value: '硫' },
  { label: '卤素相关', value: '卤素相关' },
  { label: '醚', value: '醚' },
  { label: '醛', value: '醛' },
  { label: '炔', value: '炔' },
  { label: '酮', value: '酮' },
  { label: '烯', value: '烯' },
  { label: '盐', value: '盐' },
  { label: '氧化剂', value: '氧化剂' },
  { label: '药物及天然产物', value: '药物及天然产物' },
  { label: '酯', value: '酯' },
  { label: '磷', value: '磷' },
  { label: '硼', value: '硼' },
  { label: '硅', value: '硅' },
  { label: '锡', value: '锡' },
  { label: '铜铁银', value: '铜铁银' },
  { label: '硒', value: '硒' },
  { label: '酚', value: '酚' },
  { label: '饱和&芳香烃', value: '饱和&芳香烃' },
  { label: '其他', value: '其他' },
]

